import { Button } from "@/components/ui/button";
import { FolderUp } from "lucide-react";
import React from "react";
import { Material } from "../../material/page";
import { Stock_Requisition } from "./TableMaterial";
import { toast } from "sonner";
import {
  uploadFileStock,
  UploadStock_Requisition,
} from "@/app/api/client/stock_requisition";

interface CalendarProp {
  selectedDate: string;
  material_variant: Material[];
  value: string;
  setCheck: React.Dispatch<React.SetStateAction<Stock_Requisition[]>>;
}

const UploadFile = ({
  selectedDate,
  material_variant,
  value,
  setCheck,
}: CalendarProp) => {
  const handleUploadFile = async (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    const file = event.target.files?.[0];
    if (!file) return;

    if (!selectedDate || !value) {
      toast.error("ກະລຸນາເລືອກວັນທີ່ ແລະ ສາຂາກ່ອນອັປໂຫລດ");
      event.target.value = "";
      return;
    }

    if (file.type !== "text/html" && !file.name.endsWith(".html")) {
      toast.error("ຟາຍທີ່ອັປໂຫລດບໍ່ຖືກຕ້ອງ");
      return;
    }

    const htmlText = await file.text();
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlText, "text/html");

    // Target the rows in the list table
    const rows = doc.querySelectorAll("table.list tr");
    const newRequisitions: UploadStock_Requisition[] = [];

    rows.forEach((row) => {
      const cells = row.querySelectorAll("td");

      // In your HTML, Column 1 is Barcode, Column 4 is Quantity (based on 0-index)
      // Looking at your HTML: <td>1</td> (index 0), <td>701</td> (index 1),
      // <td><img></td> (index 2), <td>[701]...</td> (index 3), <td>60 ຂີດ</td> (index 4)
      if (cells.length >= 5) {
        const barcode = cells[1]?.textContent?.trim();
        const quantityRaw = cells[4]?.textContent?.trim() || "";

        // Extract only numbers from "60 ຂີດ"
        const quantity = parseInt(quantityRaw.replace(/[^0-9]/g, ""), 10);

        if (!barcode || isNaN(quantity)) return;

        // Find the matching variant from the material_variant prop
        let matchedVariant: any = null;
        let matchedMaterialName = "";

        for (const m of material_variant) {
          const found = m.material_variant.find((v) => v.barcode === barcode);
          if (found) {
            matchedVariant = found;
            matchedMaterialName = m.name;
            break;
          }
        }

        if (matchedVariant) {
          const requisitionEntry: UploadStock_Requisition = {
            material_variantId: Number(matchedVariant.id),
            quantity: Number(quantity),
            base_quantity:
              Number(quantity) * Number(matchedVariant.conver_to_base || 1),
            price_kip: Number(matchedVariant.price_kip || 0),
            sell_price_kip: Number(matchedVariant.sell_price_kip || 0),
            price_bath: Number(matchedVariant.price_bath || 0),
            sell_price_bath: Number(matchedVariant.sell_price_bath || 0),
            date: selectedDate,
            branchId: parseInt(value),
            variant_name: matchedVariant.variant_name,
            material_name: matchedMaterialName,
          };
          newRequisitions.push(requisitionEntry as any);
        }
      }
    });

    if (newRequisitions.length > 0) {
      const response = await uploadFileStock(newRequisitions);
      setCheck((prev) => {
        // Create a map from existing state for quick lookup
        const existingMap = new Map(
          prev.map((item) => [item.material_variantId, item]),
        );

        // Loop through the items we just uploaded
        newRequisitions.forEach((item) => {
          // Map UploadStock_Requisition back to the simpler Stock_Requisition type
          const updatedItem: Stock_Requisition = {
            id: 0, // The real ID is generated by DB, 0 acts as a placeholder
            material_variantId: item.material_variantId,
            quantity: item.quantity,
            branchId: item.branchId,
          };

          // Add or Overwrite based on material_variantId
          existingMap.set(item.material_variantId, updatedItem);
        });

        // Return the new merged array
        return Array.from(existingMap.values());
      });

      toast.success(`ອັປໂຫລດສຳເລັດ ${newRequisitions.length} ລາຍການ`);
    } else {
      toast.error("ບໍ່ພົບຂໍ້ມູນສິນຄ້າທີ່ກົງກັນໃນລະບົບ");
    }

    event.target.value = ""; // Reset input so same file can be uploaded again
  };
  return (
    <div className="flex items-center">
      {/* 1. The actual input is hidden */}
      <input
        type="file"
        id="file-upload"
        accept=".html"
        className="hidden"
        onChange={handleUploadFile}
      />

      {/* 2. The Label is styled to look exactly like your Button */}
      <Button
        asChild // This allows the Button to behave like the Label inside it
        variant="outline"
        className="font-lao h-8 md:h-9 max-w-50 cursor-pointer"
      >
        <label
          htmlFor="file-upload"
          className="flex items-center gap-2 cursor-pointer"
        >
          <FolderUp className="h-4 w-4" />
          ອັປໂຫລດຟາຍ
        </label>
      </Button>
    </div>
  );
};

export default UploadFile;
